### ISSUE TITLE
Should we remove `headers` from `baseOptions` and provide composable transformers instead?

### ISSUE THREAD

**Issue by danielweinmann** [gustavoguichard/make-service#24]
As @gustavoguichard pointed out [here](https://github.com/gustavoguichard/make-service/pull/23#discussion_r1212457241), right now we're forcing our internal [headerTransformer](https://github.com/gustavoguichard/make-service/blob/next/src/api.ts#L102) to be called [after the requestTransformer](https://github.com/gustavoguichard/make-service/blob/next/src/api.ts#L113).

We can make that decision if we want, but I think it would be great if our users could do something like:

```ts
makeService('https://api.com', {
  requestTransformer: pipe(headersTransformer, snakeCaseRequestTransformer),
})
```

I have a feeling that @diogob's intent when he made [this commit](https://github.com/gustavoguichard/make-service/commit/fad85461772b1fb313bf7886aa24567101310b6f) was to ignite this discussion :) what do you guys think about this?

**Comment by gustavoguichard** [comment]
I'm also closing this one as we agreed to have a leaner API ;)
