### ISSUE TITLE
Should we allow `undefined` keys on body object and remove them from the request?

### ISSUE THREAD

**Issue by danielweinmann** [gustavoguichard/make-service#31]
```ts
function createReview(stars: number, description: string | undefined) {
  return api.post('/reviews', { body: { stars, description } })
} 
```

Right now, this example will not type-check because `undefined` is not a valid `JSONValue`. Then we end up having to do this kind of boilerplate:

```ts
function createReview(stars: number, description: string | undefined) {
  return api.post('/reviews', { body: description ? { stars, description } : { stars } })
} 
```

Should we allow undefined as a JSON value and then remove these keys from the body before making the request? This is somewhat related to #28 but I believe it deserves a separate issue :)

**Comment by gustavoguichard** [comment]
Yup! I think we should allow undefined and Date as pointed out in #28

You're welcome to make a PR otherwise I may end up doing it soon.
