### ISSUE TITLE
Wrong Content-Type when POST with FormData + File

### ISSUE THREAD

**Issue by iamandrewluca** [gustavoguichard/make-service#44]
At the moment the `Content-Type` header defaults to `application/json`

When a user submits a `FormData`, the `Content-Type` header should not be manually added.

When using a `FormData`<sup>*</sup> as `body` the browser will pick the right `Content-Type` header

When the form does not contain any `File/Blob` the header is set to `application/x-www-form-urlencoded`
When the form contains at least one `File/Blob` the header is set to `multipart/form-data` with the correct form boundary

<sup>*</sup> - this is not the case only for `FormData`, user can have different types as `body`

```
body?: null | ReadableStream | Blob | BufferSource | FormData | URLSearchParams | string
```

I suppose that `Content-Type` as `application/json` should be used only when `body` is `string` or missing, for other types usually the browser will set the correct header (`FormData` for sure, for other types need to be checked).

This is my temporary workaround with patch-package (does not cover all cases)

**patches/make-service+2.1.2.patch**

```diff
diff --git a/node_modules/make-service/dist/index.mjs b/node_modules/make-service/dist/index.mjs
index 486302c..87efd56 100644
--- a/node_modules/make-service/dist/index.mjs
+++ b/node_modules/make-service/dist/index.mjs
@@ -96,10 +96,9 @@ function typedResponse(response, options) {
 async function enhancedFetch(url, requestInit) {
   var _a, _b;
   const { query, trace, ...reqInit } = requestInit != null ? requestInit : {};
+  const tmpHeaders = reqInit.body instanceof FormData ? {} : { "content-type": "application/json" };
   const headers = mergeHeaders(
-    {
-      "content-type": "application/json"
-    },
+    tmpHeaders,
     (_a = reqInit.headers) != null ? _a : {}
   );
   const withParams = replaceURLParams(url, (_b = reqInit.params) != null ? _b : {});
```

**Comment by gustavoguichard** [comment]
Hi @iamandrewluca , thanks for reporting it!
I'm kind of regretting to add that default at this point, but to avoid a breaking change your solution seems to be good.
Do you feel like making a PR for it?
https://github.com/gustavoguichard/make-service/blob/main/src/api.ts#L78

You are more than welcome to do so and to add a test case, otherwise I'll be doing it, but probably after all the holidays and few more days to catch up on other work load.

LMK

Cheers

**Comment by gustavoguichard** [comment]
PS: @iamandrewluca , I'd probably add that default instead of removing it, and for that we need to call `ensureBodyString` before that line:
```ts
const body = ensureStringBody(reqInit.body)
const tmpHeaders = body === null || typeof body === 'string' ? { "content-type": "application/json" } : {};
```

**Comment by iamandrewluca** [comment]
Hey @gustavoguichard I can do a PR, will look into it at the end of this week, or maybe after new year.
