### ISSUE TITLE
Preprocess and transform inputs and responses for all requests

### ISSUE THREAD

**Issue by danielweinmann** [gustavoguichard/make-service#5]
We need a way to manipulate the response on `makeService`. In our case, we need to get some response headers at every request and save them to local storage. But it could be any kind of transform on the response. 

I don't have any strong opinions about the API for that, but something like a `transformResponse` option that we pass to `makeService` would work.

**Comment by danielweinmann** [comment]
Here's how we're solving for now:

```ts
const service = makeService(myBaseURL, myHeaders)

type ServiceRequestFns = ReturnType<typeof makeService>
type ServiceRequestFn = ServiceRequestFns['get']

const makeServiceRequest: (fn: ServiceRequestFn) => ServiceRequestFn =
  (fn) => async (path, init) => {
    const response = await fn(path, init)
    saveHeaders(response)
    return response
  }

const methods: (keyof ServiceRequestFns)[] = [
  'head',
  'options',
  'delete',
  'get',
  'post',
  'put',
  'patch',
]

const api = methods.reduce<ServiceRequestFns>(
  (obj, method) => ({ ...obj, [method]: makeServiceRequest(service[method]) }),
  service,
)
```

**Comment by gustavoguichard** [comment]
I think you are using a great solution, although some sort of API could be added to do that for you.
The place to add those APIs is in [`ServiceRequestInit`](https://github.com/gustavoguichard/make-service/blob/ff1849cbfdee1402e1d569996d93bcccb8edf216/src/types.ts#L27). I'm not sure I want to put many stuff there but I do see the value on something like that.

I'm going to think about other stuff to be adding there, I accept any suggestions.

I don't think those extra options should go into the `enhancedFetch` method as it is an one-off replacement for `fetch` whilst `makeService` is a setup for sub-sequential requests.

Thoughts?

**Comment by danielweinmann** [comment]
Interesting, but I'm happy with the solution above for now. And I also like a thin API :)

**Comment by danielweinmann** [comment]
@gustavoguichard, I reopened this issue now that we have the transformers in place. I think we should add options on `makeService` and `makeFetcher` to:

* Preprocess all responses before validating against the schema
* Transform all `query` objects
* Transform all `params` objects
* Transform all `body` objects

I'm happy to contribute a PR, but I want to make sure we have an agreed-upon API first :) what do you think?

**Comment by gustavoguichard** [comment]
@danielweinmann I'd love to get a PR from you.

I see this API as a breaking change though...

Currently for `makeService` and `makeFetcher` the second argument represents the `baseHeaders?: HeadersInit | (() => HeadersInit | Promise<HeadersInit>)` and I'm thinking about making this second argument an object that accepts `baseHeaders` but also accepts other options such as the suggested `preprocessResponse`, `preprocessBody`, and `preprocessQuery` (I didn't think thoroughly about names though).

This would allow the API to expand even more in the future.

```ts
declare function makeService(
  baseURL: string | URL,
  baseOptions: {
    headers?: HeadersInit | (() => HeadersInit | Promise<HeadersInit>),
    preprocessResponse: <T>(payload: T) => SomeTransformation<T>,
    // ...
  },
): 
```

We should think about the accepted types for those responses though in a way it doesn't break the inference.

What do you think about it, did you have any other ideas in mind?

**Comment by danielweinmann** [comment]
I like @diogob's suggestion! What if we added only a third optional `baseOptions` parameter to `makeService`, and leave the first 2 as is?

`baseOptions` would initially only have `requestTransformer` and `responseTransformer`, but could grow to other options in the future.

I have nothing against making a breaking change, also. You decide :) we'll upgrade either way :)

**Comment by gustavoguichard** [comment]
I think the 2 suggested approaches could also be converged...
My problem with the 3rd parameter is because I'm currently designing [this future API](#3) which uses that arity.

I do accept suggestions about converging all the designs.
Without thinking too much I'm open to introduce a breaking change and have `makeService(baseURL, baseOptions?, routes?)` but it could also be `makeService(baseURL, baseHeaders, baseOptions: { requestTransformer, responseTransformer, routes })` ...

I'm really not sure about it... would love inputs from y'all.

**Comment by gustavoguichard** [comment]
Disclaimer: for clarification, I think the #3 API design is priority over this issue although I like this proposal.

**Comment by danielweinmann** [comment]
Let's go with the breaking change, then. Can I proceed with `makeService(baseURL, baseOptions?)` and then on #3 you add the `routes?` param?

**Comment by gustavoguichard** [comment]
Yup! Do you guys think I should go with the ternary option when introducing `routes` (👍) or should it go as part of `baseOptions` (🚀)?

**Comment by danielweinmann** [comment]
The problem with the third argument is that it forces people to pass the second one :) in our use cases, I don't see us not passing at least one option, so the 3rd arg feels better. But I don't know if other people would feel differently.

**Comment by diogob** [comment]
> The problem with the third argument is that it forces people to pass the second one :) in our use cases, I don't see us not passing at least one option, so the 3rd arg feels better. But I don't know if other people would feel differently.

one can always [flip](https://lodash.com/docs/4.17.15#flip)
